In [46]:
pip install matplotlib


Note: you may need to restart the kernel to use updated packages.


In [47]:
import matplotlib.pyplot as plt

In [48]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

import numpy as np

In [49]:
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.preprocessing import LabelEncoder

In [50]:
data = pd.read_csv('car.data')

In [51]:
print(data.head())

  buying  maint doors person lug_boot saftey  class
0  vhigh  vhigh     2      2    small    low  unacc
1  vhigh  vhigh     2      2    small    med  unacc
2  vhigh  vhigh     2      2    small   high  unacc
3  vhigh  vhigh     2      2      med    low  unacc
4  vhigh  vhigh     2      2      med    med  unacc


In [52]:
X = data[[
    'buying',
    'maint',
    'saftey'
]].values

In [53]:
y = data[['class']]

In [54]:
print (X, y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [55]:
Le = LabelEncoder()
for i in range(len(X[0])):
    X[:,i] = Le.fit_transform(X[:, i])

In [56]:
print (X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [57]:
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

In [58]:
y['class'] = y['class'].map(label_mapping)
y = np.array(y)

C:\Users\Suraj\AppData\Local\Temp/ipykernel_7824/3348067204.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [59]:
print (y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


In [60]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights= 'uniform')

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [68]:
knn.fit(X_train, y_train)

C:\Users\Suraj\miniconda3\envs\tf2\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [69]:
prediction = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, prediction)
print("predicitions:", prediction)
print("accuracy:", accuracy)

predicitions: [3 1 0 1 0 1 1 1 1 1 0 0 0 3 1 3 1 1 0 1 0 0 0 0 0 0 0 0 0 0 3 1 0 3 0 0 0
 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 3 0 1 1 1 1 1 0 0 1 0 1 0 1 0 1
 0 0 0 0 1 0 0 0 2 0 0 0 0 0 1 2 0 0 0 0 0 0 0 2 0 1 0 1 0 0 0 1 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 2 0 0 2 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 3 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 3 1 0 0 0 0 0 0 0 1 0 1 0 0 2 0 0 1 0 0 0 0 0 1 0 2 0 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 1 0 3 0 0 0 1 1 0 0 3 0 0 0 0 3 0 1 1 0 0 0 0 0 1 0 1 0 0 3 0
 3 0 0 3 0 1 0 1 0 0 0 0 0 0 3 0 0 0 3 0 1 1 0 1 0 1 0 0 2 1 0 0 0 0 3 0 0
 0 3 1 0 1 3 0 0 0 0 1 0 0]
accuracy: 0.7456647398843931
